spring:
datasource:
url: jdbc:postgresql://localhost:5432/acebook_springboot_test
username: your-username
password: your-password
jpa:
properties:
hibernate:
temp:
use_jdbc_metadata_defaults: false
database-platform: org.hibernate.dialect.PostgreSQL9Dialect

flyway:
baseline-on-migrate: true
