name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112786669.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image for multiple platforms
        run: |
          # Enable experimental features in Docker
          export DOCKER_CLI_EXPERIMENTAL=enabled

          # Create a new builder instance with Buildx
          docker buildx create --use --name mybuilder

          # Build the Docker image for multiple platforms
          docker buildx build --platform linux/amd64,linux/arm64 -t socialites-app01 --push .

          # Clean up after build
          docker buildx rm mybuilder

      - name: List images in ECR
        run: aws ecr describe-images --repository-name socialites-app01 --region us-east-1
