name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Replace with your AWS region

      - name: Login to Amazon ECR Public Registry
        run: aws ecr-public get-login-password --region eu-west-2 | docker login --username AWS --password-stdin public.ecr.aws/c3e7w6l3

      - name: Build and push Docker image to Amazon ECR Public
        env:
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/c3e7w6l3/socialites-app:${IMAGE_TAG} --push .
